#!/bin/bash
# ------------------------------------------------------------
# Arch Linux - System Restoration Script
# Generated by DSXConfig v2.0.0
# Timestamp: 2026-04-01 10:56:08
# Distro: arch | Package Manager: pacman
# ------------------------------------------------------------

set -e  # Exit on error
set -u  # Exit on undefined variable

# System detection
detect_system() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO_ID=$ID
        PRETTY_NAME=$PRETTY_NAME
    else
        DISTRO_ID="unknown"
        PRETTY_NAME="Unknown Linux"
    fi

    # Detect package manager
    if command -v pacman >/dev/null 2>&1; then
        PKG_MGR="pacman"
    elif command -v apt >/dev/null 2>&1; then
        PKG_MGR="apt"
    elif command -v dnf >/dev/null 2>&1; then
        PKG_MGR="dnf"
    else
        PKG_MGR="unknown"
    fi
}

get_update_command() {
    case "$DISTRO_ID" in
        arch|archlinux)
            echo "sudo pacman -Syu --noconfirm"
            ;;
        fedora|rhel|centos)
            echo "sudo dnf update -y"
            ;;
        debian|ubuntu|linuxmint)
            echo "sudo apt update && sudo apt upgrade -y"
            ;;
        *)
            echo "echo 'No update command available for $DISTRO_ID'"
            ;;
    esac
}

# Call detection
detect_system

echo "================================================"
echo "  DSXConfig System Restoration"
echo "  Target: $PRETTY_NAME"
echo "================================================"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'  # No Color

# Logging functions
VERBOSE=false

select_log_mode() {
    if command -v fzf >/dev/null 2>&1; then
        answer=$(printf "Sim
Nao" | fzf --no-multi --height 4 --border --prompt "Mostrar logs de instalacao? ")
        [ "$answer" = "Sim" ] && VERBOSE=true
    else
        read -p "Mostrar logs de instalacao? [s/N] " answer
        if [[ "$answer" =~ ^[sS](im)?$ ]]; then
            VERBOSE=true
        fi
    fi
}

progress_bar() {
    local current=$1
    local total=$2
    local width=40
    local filled=$(( current * width / total ))
    local empty=$(( width - filled ))
    local percent=$(( current * 100 / total ))
    printf "Progress: ["
    for i in $(seq 1 $filled); do printf "#"; done
    for i in $(seq 1 $empty); do printf "-"; done
    printf "] %3d%%" "$percent"
    if [ "$current" -ge "$total" ]; then echo; fi
}

log_info() {
    if [ "$VERBOSE" = "true" ]; then
        echo -e "${GREEN}[INFO]${NC} $1"
    fi
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

select_log_mode

# Step 1: Update system
log_info "Updating system repositories..."
UPDATE_CMD=$(get_update_command)
if ! eval "$UPDATE_CMD"; then
    log_error "Failed to update system"
    exit 1
fi
log_info "System update completed"
echo ""

# Adaptive package mapping for cross-distro resiliency
TARGET_PKG_MGR="$PKG_MGR"

map_package() {
    local pkg="$1"
    local target_pkg="$pkg"

    case "$pkg" in
        python)
            if [ "$TARGET_PKG_MGR" = "pacman" ]; then
                target_pkg="python"
            else
                target_pkg="python3"
            fi
            ;;
        python-pip)
            target_pkg="python3-pip";
            ;;
        libreoffice-fresh)
            target_pkg="libreoffice";
            ;;
        google-chrome|google-chrome-stable)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="google-chrome-stable"
                    ;;
                dnf)
                    target_pkg="google-chrome-stable"
                    ;;
                pacman)
                    target_pkg="google-chrome"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        docker)
            if [ "$TARGET_PKG_MGR" = "apt" ]; then
                target_pkg="docker.io"
            else
                target_pkg="docker"
            fi
            ;;
        openssh)
            target_pkg="openssh-server";
            ;;
        code|vscode|visual-studio-code)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="code"
                    ;;
                dnf)
                    target_pkg="code"
                    ;;
                pacman)
                    target_pkg="visual-studio-code-bin"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        github-desktop|github-desktop-bin)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="github-desktop"
                    ;;
                dnf)
                    target_pkg="github-desktop"
                    ;;
                pacman)
                    target_pkg="github-desktop-bin"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        spotify)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="spotify-client"
                    ;;
                dnf)
                    target_pkg="spotify-client"
                    ;;
                pacman)
                    target_pkg="spotify"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        obsidian)
            target_pkg="obsidian";
            ;;
        *)
            target_pkg="$pkg";
            ;;
    esac

    echo "$target_pkg"
}

package_available() {
    local pkg="$1"
    case "$TARGET_PKG_MGR" in
        pacman)
            pacman -Si "$pkg" >/dev/null 2>&1
            ;;
        apt)
            apt-cache show "$pkg" >/dev/null 2>&1
            ;;
        dnf)
            dnf list --available "$pkg" >/dev/null 2>&1
            ;;
        *)
            return 1
            ;;
    esac
}

check_flatpak() {
    local pkg="$1"
    flatpak search "$pkg" --columns=application | grep -q "^$pkg$" 2>/dev/null
}

check_snap() {
    local pkg="$1"
    snap find "$pkg" | grep -q "^$pkg " 2>/dev/null
}

check_aur() {
    local pkg="$1"
    # Simple check if AUR package exists (requires yay/paru or similar)
    if command -v yay >/dev/null 2>&1; then
        yay -Si "$pkg" >/dev/null 2>&1
    elif command -v paru >/dev/null 2>&1; then
        paru -Si "$pkg" >/dev/null 2>&1
    else
        return 1
    fi
}

find_installation_methods() {
    local pkg="$1"
    local methods=""

    if package_available "$pkg"; then
        methods="${methods}native "
    fi

    if check_flatpak "$pkg"; then
        methods="${methods}flatpak "
    fi

    if [ "$TARGET_PKG_MGR" = "apt" ] && check_snap "$pkg"; then
        methods="${methods}snap "
    fi

    if [ "$TARGET_PKG_MGR" = "pacman" ] && check_aur "$pkg"; then
        methods="${methods}aur "
    fi

    echo "$methods" | tr ' ' '
' | grep -v '^$'
}

choose_installation_method() {
    local pkg="$1"
    local methods="$2"

    if [ -z "$methods" ]; then
        log_error "Nenhum metodo de instalacao encontrado para $pkg"
        return 1
    fi

    local method_count=$(echo "$methods" | wc -l)

    if [ "$method_count" -eq 1 ]; then
        echo "$methods"
        return 0
    fi

    log_info "Multiplos metodos disponiveis para $pkg:"
    echo "$methods" | nl -w2 -s') '

    if command -v fzf >/dev/null 2>&1; then
        local choice=$(echo "$methods" | fzf --no-multi --height 10 --border --prompt "Escolha metodo para $pkg: ")
        echo "$choice"
    else
        local choice
        read -p "Escolha numero do metodo para $pkg: " choice_num
        echo "$methods" | sed -n "${choice_num}p"
    fi
}

install_with_method() {
    local pkg="$1"
    local method="$2"

    case "$method" in
        native)
            case "$TARGET_PKG_MGR" in
                pacman)
                    sudo pacman -S --needed --noconfirm "$pkg"
                    ;;
                apt)
                    sudo apt install -y "$pkg"
                    ;;
                dnf)
                    sudo dnf install -y "$pkg"
                    ;;
                *)
                    log_error "Gerenciador de pacotes nao suportado: $TARGET_PKG_MGR"
                    return 1
                    ;;
            esac
            ;;
        flatpak)
            flatpak install -y flathub "$pkg"
            ;;
        snap)
            sudo snap install "$pkg"
            ;;
        aur)
            if command -v yay >/dev/null 2>&1; then
                yay -S --needed --noconfirm "$pkg"
            elif command -v paru >/dev/null 2>&1; then
                paru -S --needed --noconfirm "$pkg"
            else
                log_error "Nenhum helper AUR encontrado (yay/paru)"
                return 1
            fi
            ;;
        *)
            log_error "Metodo desconhecido: $method"
            return 1
            ;;
    esac
}

suggest_alternatives() {
    local pkg="$1"
    case "$pkg" in
        code|vscode|visual-studio-code)
            log_info "Alternativas para VSCode: flatpak install code, snap install code, ou baixar .deb/.rpm do site oficial"
            ;;
        google-chrome|chromium)
            log_info "Alternativas para Chrome: chromium-browser (apt), chromium (dnf), ou flatpak install com.google.Chrome"
            ;;
        obsidian)
            log_info "Alternativas para Obsidian: flatpak install md.obsidian.Obsidian"
            ;;
        discord)
            log_info "Alternativas para Discord: flatpak install com.discordapp.Discord"
            ;;
        spotify)
            log_info "Alternativas para Spotify: flatpak install com.spotify.Client"
            ;;
        *)
            log_info "Tente flatpak search '$pkg' ou snap find '$pkg' para alternativas"
            ;;
    esac
}

install_google_chrome() {
    # ask once per script if user wants this behavior
    read -p "Instalar Google Chrome via repositorio oficial para $TARGET_PKG_MGR? [S/n] " choice
    if [[ "$choice" =~ ^[nN] ]]; then
        return 0
    fi

    case "$TARGET_PKG_MGR" in
        apt)
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /etc/apt/keyrings/google-linux-signing-key.gpg
            echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install -y google-chrome-stable
            ;;
        dnf)
            sudo tee /etc/yum.repos.d/google-chrome.repo >/dev/null <<'EOF'
[google-chrome]
name=google-chrome - x86_64
baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
EOF
            sudo dnf install -y google-chrome-stable
            ;;
        pacman)
            log_warn "Use AUR helper para instalar google-chrome no Arch.";
            return 1;
            ;;
        *)
            log_error "Google Chrome nao suportado para $TARGET_PKG_MGR";
            return 1;
            ;;
    esac
}

install_vscode() {
    # ask once per script if user wants this behavior
    read -p "Instalar VSCode via repositorio oficial da Microsoft para $TARGET_PKG_MGR? [S/n] " choice
    if [[ "$choice" =~ ^[nN] ]]; then
        return 0
    fi

    case "$TARGET_PKG_MGR" in
        apt)
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/packages.microsoft.gpg
            echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main' | sudo tee /etc/apt/sources.list.d/vscode.list
            sudo apt update
            sudo apt install -y code
            ;;
        dnf)
            sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
            sudo tee /etc/yum.repos.d/vscode.repo >/dev/null <<'EOF'
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
EOF
            sudo dnf install -y code
            ;;
        pacman)
            log_warn "Use AUR helper para instalar vscode no Arch.";
            return 1;
            ;;
        *)
            log_error "VSCode nao suportado para $TARGET_PKG_MGR";
            return 1;
            ;;
    esac
}

install_package() {
    local pkg="$1"

    if [ "$pkg" = "google-chrome" ] || [ "$pkg" = "google-chrome-stable" ]; then
        install_google_chrome
        return
    fi
    if [ "$pkg" = "code" ] || [ "$pkg" = "vscode" ] || [ "$pkg" = "visual-studio-code" ]; then
        install_vscode
        return
    fi

    local methods=$(find_installation_methods "$pkg")
    if [ -z "$methods" ]; then
        log_error "Pacote $pkg nao encontrado em nenhuma fonte disponivel"
        log_info "Tentando alternativas logicas..."
        suggest_alternatives "$pkg"
        return 1
    fi

    local chosen_method=$(choose_installation_method "$pkg" "$methods")
    if [ -z "$chosen_method" ]; then
        log_warn "Instalacao de $pkg cancelada pelo usuario"
        return 1
    fi

    log_info "Instalando $pkg via $chosen_method"
    if ! install_with_method "$pkg" "$chosen_method"; then
        log_error "Falha ao instalar $pkg via $chosen_method"
        return 1
    fi
}

PACKAGES=(git python)

# Step 2: Install native packages
if [ ${#PACKAGES[@]} -gt 0 ]; then
    total=${#PACKAGES[@]}
    current=0
    for original in "${PACKAGES[@]}"; do
        current=$((current + 1))
        progress_bar "$current" "$total"

        candidate="$(map_package "$original")"

        if package_available "$candidate"; then
            if [ "$VERBOSE" = "true" ]; then
                log_info "Instalando pacote resolvido '$candidate' de '$original'"
            fi
            if ! install_package "$candidate"; then
                log_warn "Falha ao instalar '$candidate'"
            fi
        else
            log_warn "Pulando '$original' (nao disponivel como '$candidate')"
        fi
    done
    progress_bar "$total" "$total"
else
    log_warn "No native packages to install"
fi

echo ""
# Step 4: Install Flatpak applications
log_info "Installing 1 Flatpak applications..."
if command -v flatpak &> /dev/null; then
    log_info "Adding flathub remote if not present..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true
    
    if ! flatpak install -y flathub org.mozilla.firefox; then
        log_warn "Some Flatpak applications may have failed to install"
    fi
    log_info "Flatpak installation completed"
else
    log_error "Flatpak is not installed. Please install it manually."
fi
echo ""

echo ""
echo "================================================"
log_info "Restoration complete!"
log_info "Your system is ready to use."
echo "================================================"
