"""Script generation and export module."""

import os
import shlex
from datetime import datetime
from typing import List, Optional
from constants import (
    UPDATE_COMMANDS,
    INSTALL_COMMANDS,
    SCRIPT_PREFIX,
    SCRIPT_EXTENSION,
    SCRIPT_ENCODING,
    SCRIPT_PERMISSIONS,
)
from core.detector import SystemInfo
from core.config import SystemConfig
from tui.interface import TUI
from logger import get_logger

logger = get_logger(__name__)

__all__ = ["ScriptExporter"]


class ScriptExporter:
    """
    Generates restoration scripts based on system information and packages.

    Attributes:
        sys: SystemInfo instance
        filename: Generated script filename
    """

    def __init__(self, sys_info: SystemInfo) -> None:
        """
        Initialize ScriptExporter.

        Args:
            sys_info: SystemInfo instance with system details
        """
        self.sys = sys_info
        timestamp = datetime.now().strftime("%Y%m%d")
        self.filename = f"{SCRIPT_PREFIX}{timestamp}{SCRIPT_EXTENSION}"
        logger.info(f"ScriptExporter initialized for {self.sys.distro}")

    def confirm(self, prompt: str) -> bool:
        """
        Ask user for confirmation using fzf.

        Args:
            prompt: Question to display to user

        Returns:
            True if user selected "Yes", False otherwise
        """
        try:
            choice = TUI.run_fzf(["Yes", "No"], prompt=prompt)
            result = choice == "Yes"
            logger.debug(f"User confirmation for '{prompt}': {result}")
            return result
        except Exception as e:
            logger.error(f"Error during confirmation: {e}")
            return False

    def generate_script(
        self, packages: List[str], aur_packages: List[str], flatpaks: List[str], system_config: Optional[SystemConfig] = None
    ) -> Optional[str]:
        """
        Generate restoration script with all collected data.

        Args:
            packages: List of native packages
            aur_packages: List of AUR packages
            flatpaks: List of Flatpak applications
            system_config: Optional system configuration to include

        Returns:
            Path to generated script, None if generation failed

        Raises:
            ValueError: If input lists are invalid
        """
        if not isinstance(packages, list):
            raise ValueError("packages must be a list")
        if not isinstance(aur_packages, list):
            raise ValueError("aur_packages must be a list")
        if not isinstance(flatpaks, list):
            raise ValueError("flatpaks must be a list")

        try:
            script_content = self._build_script(packages, aur_packages, flatpaks, system_config)
            self._write_script(script_content)
            logger.info(f"Script generated successfully: {self.filename}")
            return self.filename
        except Exception as e:
            logger.error(f"Failed to generate script: {e}")
            return None

    def _build_script(
        self, packages: List[str], aur_packages: List[str], flatpaks: List[str], system_config: Optional[SystemConfig] = None
    ) -> str:
        """
        Build script content.

        Args:
            packages: List of native packages
            aur_packages: List of AUR packages
            flatpaks: List of Flatpak applications
            system_config: Optional system configuration to include

        Returns:
            Complete script content as string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        script = f"""#!/bin/bash
# {'-' * 60}
# {self.sys.name} - System Restoration Script
# Generated by DSXConfig v2.0.0
# Timestamp: {timestamp}
# Distro: {self.sys.distro} | Package Manager: {self.sys.pkg_mgr}
# {'-' * 60}

set -e  # Exit on error
set -u  # Exit on undefined variable

# System detection
detect_system() {{
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO_ID=$ID
        PRETTY_NAME=$PRETTY_NAME
    else
        DISTRO_ID="unknown"
        PRETTY_NAME="Unknown Linux"
    fi

    # Detect package manager
    if command -v pacman >/dev/null 2>&1; then
        PKG_MGR="pacman"
    elif command -v apt >/dev/null 2>&1; then
        PKG_MGR="apt"
    elif command -v dnf >/dev/null 2>&1; then
        PKG_MGR="dnf"
    else
        PKG_MGR="unknown"
    fi
}}

get_update_command() {{
    case "$DISTRO_ID" in
        arch|archlinux)
            echo "sudo pacman -Syu --noconfirm"
            ;;
        fedora|rhel|centos)
            echo "sudo dnf update -y"
            ;;
        debian|ubuntu|linuxmint)
            echo "sudo apt update && sudo apt upgrade -y"
            ;;
        *)
            echo "echo 'No update command available for $DISTRO_ID'"
            ;;
    esac
}}

# Call detection
detect_system

echo "================================================"
echo "  DSXConfig System Restoration"
echo "  Target: $PRETTY_NAME"
echo "================================================"
echo ""

# Color codes
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'  # No Color

# Logging functions
log_info() {{
    echo -e "${{GREEN}}[INFO]${{NC}} $1"
}}

log_warn() {{
    echo -e "${{YELLOW}}[WARN]${{NC}} $1"
}}

log_error() {{
    echo -e "${{RED}}[ERROR]${{NC}} $1"
}}

# Step 1: Update system
log_info "Updating system repositories..."
UPDATE_CMD=$(get_update_command)
if ! $UPDATE_CMD; then
    log_error "Failed to update system"
    exit 1
fi
log_info "System update completed"
echo ""

# Adaptive package mapping for cross-distro resiliency
TARGET_PKG_MGR="$PKG_MGR"

map_package() {{
    local pkg="$1"
    local target_pkg="$pkg"

    case "$pkg" in
        python)
            if [ "$TARGET_PKG_MGR" = "pacman" ]; then
                target_pkg="python"
            else
                target_pkg="python3"
            fi
            ;;
        python-pip)
            target_pkg="python3-pip";
            ;;
        libreoffice-fresh)
            target_pkg="libreoffice";
            ;;
        docker)
            if [ "$TARGET_PKG_MGR" = "apt" ]; then
                target_pkg="docker.io"
            else
                target_pkg="docker"
            fi
            ;;
        openssh)
            target_pkg="openssh-server";
            ;;
        *)
            target_pkg="$pkg";
            ;;
    esac

    echo "$target_pkg"
}}

package_available() {{
    local pkg="$1"
    case "$TARGET_PKG_MGR" in
        pacman)
            pacman -Si "$pkg" >/dev/null 2>&1
            ;;
        apt)
            apt-cache show "$pkg" >/dev/null 2>&1
            ;;
        dnf)
            dnf list --available "$pkg" >/dev/null 2>&1
            ;;
        *)
            return 1
            ;;
    esac
}}

install_package() {{
    local pkg="$1"
    case "$TARGET_PKG_MGR" in
        pacman)
            sudo pacman -S --needed --noconfirm "$pkg";
            ;;
        apt)
            sudo apt install -y "$pkg";
            ;;
        dnf)
            sudo dnf install -y "$pkg";
            ;;
        *)
            log_error "Unsupported package manager: $TARGET_PKG_MGR";
            return 1;
            ;;
    esac
}}

ask_install_choice() {{
    local orig_pkg="$1"
    local candidate_pkg="$2"

    echo "Package '$orig_pkg' not found by default. Suggested candidate is '$candidate_pkg'."
    read -p "Install candidate '$candidate_pkg'? [y/N] " answer
    if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
        echo "$candidate_pkg"
    else
        echo ""
    fi
}}

PACKAGES=({self._quote_packages(packages)})

# Step 2: Install native packages
if [ ${{#PACKAGES[@]}} -gt 0 ]; then
    log_info "Installing ${{#PACKAGES[@]}} native packages ($TARGET_PKG_MGR) with adaptive mapping..."
    for original in "${{PACKAGES[@]}}"; do
        candidate="$(map_package "$original")"

        if package_available "$candidate"; then
            log_info "Installing resolved package '$candidate' for source '$original'"
            if ! install_package "$candidate"; then
                log_warn "Failed to install '$candidate'"
            fi
            continue
        fi

        choice="$(ask_install_choice "$original" "$candidate")"
        if [ -n "$choice" ]; then
            if ! install_package "$choice"; then
                log_warn "Failed to install chosen package '$choice'"
            fi
        else
            log_warn "Skipped package '$original'"
        fi
    done
    log_info "Native package installation completed"
else
    log_warn "No native packages to install"
fi

echo ""
"""

        # Add AUR section if applicable
        if aur_packages:
            script += self._build_aur_section(aur_packages)

        # Add Flatpak section
        if flatpaks:
            script += self._build_flatpak_section(flatpaks)

        # Add system configuration section
        if system_config:
            script += self._build_config_section(system_config)

        # Footer
        script += """
echo ""
echo "================================================"
log_info "Restoration complete!"
log_info "Your system is ready to use."
echo "================================================"
"""

        return script

    def _build_aur_section(self, aur_packages: List[str]) -> str:
        """Build AUR installation section."""
        packages_str = self._quote_packages(aur_packages)
        return f"""# Step 3: Install AUR packages (Arch Linux)
if [ "$DISTRO_ID" = "arch" ] || [ "$DISTRO_ID" = "archlinux" ]; then
    log_info "Installing {len(aur_packages)} AUR packages..."
    if command -v yay &> /dev/null; then
        if ! yay -S --needed --noconfirm {packages_str}; then
            log_warn "Some AUR packages may have failed to install"
        fi
        log_info "AUR package installation completed"
    elif command -v paru &> /dev/null; then
        if ! paru -S --needed --noconfirm {packages_str}; then
            log_warn "Some AUR packages may have failed to install"
        fi
        log_info "AUR package installation completed (using paru)"
    else
        log_error "Neither yay nor paru found. Install an AUR helper to proceed."
    fi
else
    log_warn "AUR packages skipped (not Arch Linux)"
fi
echo ""
"""

    def _build_flatpak_section(self, flatpaks: List[str]) -> str:
        """Build Flatpak installation section."""
        packages_str = self._quote_packages(flatpaks)
        return f"""# Step 4: Install Flatpak applications
log_info "Installing {len(flatpaks)} Flatpak applications..."
if command -v flatpak &> /dev/null; then
    log_info "Adding flathub remote if not present..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true
    
    if ! flatpak install -y flathub {packages_str}; then
        log_warn "Some Flatpak applications may have failed to install"
    fi
    log_info "Flatpak installation completed"
else
    log_error "Flatpak is not installed. Please install it manually."
fi
echo ""
"""

    def _build_config_section(self, system_config: SystemConfig) -> str:
        """Build system configuration restoration section."""
        config_lines = []

        # Add shell configuration
        if system_config.shell:
            config_lines.append(f"log_info \"Setting user shell to {system_config.shell}...\"")
            config_lines.append(f"chsh -s /bin/{system_config.shell} || log_warn \"Failed to set shell\"")

        # Add terminal configuration (if detected)
        if system_config.terminal and system_config.terminal != "unknown":
            config_lines.append(f"log_info \"Detected terminal: {system_config.terminal}\"")
            config_lines.append("# Note: Terminal configuration may need manual setup")

        # Add environment variables
        if system_config.environment_vars:
            config_lines.append("log_info \"Setting environment variables...\"")
            for var, value in system_config.environment_vars.items():
                if var == "PATH":
                    # Handle PATH specially to avoid overriding system PATH
                    config_lines.append(f"export {var}=\"{value}:$PATH\"")
                else:
                    config_lines.append(f"export {var}=\"{value}\"")
            # Add to .bashrc if it exists
            config_lines.append("if [ -f ~/.bashrc ]; then")
            for var, value in system_config.environment_vars.items():
                if var == "PATH":
                    config_lines.append(f"    echo 'export {var}=\"{value}:$PATH\"' >> ~/.bashrc")
                else:
                    config_lines.append(f"    echo 'export {var}=\"{value}\"' >> ~/.bashrc")
            config_lines.append("fi")

        # Add config files restoration
        if system_config.config_files:
            config_lines.append("log_info \"Restoring configuration files...\"")
            for file_path, content in system_config.config_files.items():
                # Create directory if needed
                dir_path = os.path.dirname(file_path)
                if dir_path != "~":
                    config_lines.append(f"mkdir -p {dir_path}")
                # Write content using cat with heredoc
                config_lines.append(f"cat > {file_path} << 'EOF'")
                # Escape single quotes in content
                escaped_content = content.replace("'", "'\"'\"'")
                config_lines.append(escaped_content)
                config_lines.append("EOF")
                config_lines.append(f"log_info \"Restored {os.path.basename(file_path)}\"")

        if config_lines:
            section = f"""# Step 5: Restore System Configuration
log_info "Restoring system configuration..."
{"\n".join(config_lines)}
log_info "System configuration restored"
echo ""
"""
            return section
        else:
            return ""

    def _quote_packages(self, packages: List[str]) -> str:
        """
        Safely quote packages for shell execution.

        Args:
            packages: List of package names

        Returns:
            Space-separated quoted package names
        """
        return " ".join(shlex.quote(pkg) for pkg in packages)

    def _get_update_command(self) -> str:
        """Get system update command for current distro."""
        cmd = UPDATE_COMMANDS.get(self.sys.distro, UPDATE_COMMANDS.get("debian"))
        return cmd if cmd else "echo 'No update command available'"

    def _get_install_command(self, packages: List[str]) -> str:
        """
        Get package install command for current distro.

        Args:
            packages: List of packages to install

        Returns:
            Complete install command
        """
        if not packages:
            return "echo 'No packages to install'"

        base_cmd = INSTALL_COMMANDS.get(
            self.sys.distro, INSTALL_COMMANDS.get("debian")
        )
        packages_str = self._quote_packages(packages)
        return f"{base_cmd} {packages_str}" if base_cmd else "echo 'Error: Unknown distro'"

    def _write_script(self, content: str) -> None:
        """
        Write script to file and set permissions.

        Args:
            content: Script content to write

        Raises:
            IOError: If file writing fails
        """
        try:
            with open(self.filename, "w", encoding=SCRIPT_ENCODING) as f:
                f.write(content)
            os.chmod(self.filename, SCRIPT_PERMISSIONS)
            logger.info(f"Script written to {self.filename} with executable permissions")
        except IOError as e:
            logger.error(f"Failed to write script file: {e}")
            raise
