"""Script generation and export module."""

import os
import shlex
from datetime import datetime
from typing import List, Optional
from constants import (
    UPDATE_COMMANDS,
    INSTALL_COMMANDS,
    SCRIPT_PREFIX,
    SCRIPT_EXTENSION,
    SCRIPT_ENCODING,
    SCRIPT_PERMISSIONS,
)
from core.detector import SystemInfo
from tui.interface import TUI
from logger import get_logger

logger = get_logger(__name__)

__all__ = ["ScriptExporter"]


class ScriptExporter:
    """
    Generates restoration scripts based on system information and packages.

    Attributes:
        sys: SystemInfo instance
        filename: Generated script filename
    """

    def __init__(self, sys_info: SystemInfo) -> None:
        """
        Initialize ScriptExporter.

        Args:
            sys_info: SystemInfo instance with system details
        """
        self.sys = sys_info
        timestamp = datetime.now().strftime("%Y%m%d")
        self.filename = f"{SCRIPT_PREFIX}{timestamp}{SCRIPT_EXTENSION}"
        logger.info(f"ScriptExporter initialized for {self.sys.distro}")

    def confirm(self, prompt: str) -> bool:
        """
        Ask user for confirmation using fzf.

        Args:
            prompt: Question to display to user

        Returns:
            True if user selected "Yes", False otherwise
        """
        try:
            choice = TUI.run_fzf(["Yes", "No"], prompt=prompt)
            result = choice == "Yes"
            logger.debug(f"User confirmation for '{prompt}': {result}")
            return result
        except Exception as e:
            logger.error(f"Error during confirmation: {e}")
            return False

    def generate_script(
        self, packages: List[str], aur_packages: List[str], flatpaks: List[str]
    ) -> Optional[str]:
        """
        Generate restoration script with all collected data.

        Args:
            packages: List of native packages
            aur_packages: List of AUR packages
            flatpaks: List of Flatpak applications

        Returns:
            Path to generated script, None if generation failed

        Raises:
            ValueError: If input lists are invalid
        """
        if not isinstance(packages, list):
            raise ValueError("packages must be a list")
        if not isinstance(aur_packages, list):
            raise ValueError("aur_packages must be a list")
        if not isinstance(flatpaks, list):
            raise ValueError("flatpaks must be a list")

        try:
            script_content = self._build_script(packages, aur_packages, flatpaks)
            self._write_script(script_content)
            logger.info(f"Script generated successfully: {self.filename}")
            return self.filename
        except Exception as e:
            logger.error(f"Failed to generate script: {e}")
            return None

    def _build_script(
        self, packages: List[str], aur_packages: List[str], flatpaks: List[str]
    ) -> str:
        """
        Build script content.

        Args:
            packages: List of native packages
            aur_packages: List of AUR packages
            flatpaks: List of Flatpak applications

        Returns:
            Complete script content as string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        script = f"""#!/bin/bash
# {'-' * 60}
# {self.sys.name} - System Restoration Script
# Generated by DSXConfig v2.0.0
# Timestamp: {timestamp}
# Distro: {self.sys.distro} | Package Manager: {self.sys.pkg_mgr}
# {'-' * 60}

set -e  # Exit on error
set -u  # Exit on undefined variable

echo "================================================"
echo "  DSXConfig System Restoration"
echo "  Target: {self.sys.name}"
echo "================================================"
echo ""

# Color codes
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'  # No Color

# Logging functions
log_info() {{
    echo -e "${{GREEN}}[INFO]${{NC}} $1"
}}

log_warn() {{
    echo -e "${{YELLOW}}[WARN]${{NC}} $1"
}}

log_error() {{
    echo -e "${{RED}}[ERROR]${{NC}} $1"
}}

# Step 1: Update system
log_info "Updating system repositories..."
if ! {self._get_update_command()}; then
    log_error "Failed to update system"
    exit 1
fi
log_info "System update completed"
echo ""

# Step 2: Install native packages
if [ {len(packages)} -gt 0 ]; then
    log_info "Installing {len(packages)} native packages ({self.sys.pkg_mgr})..."
    if ! {self._get_install_command(packages)}; then
        log_warn "Some packages may have failed to install"
    fi
    log_info "Native package installation completed"
else
    log_warn "No native packages to install"
fi
echo ""
"""

        # Add AUR section if applicable
        if aur_packages and self.sys.distro in ["arch", "archlinux"]:
            script += self._build_aur_section(aur_packages)

        # Add Flatpak section
        if flatpaks:
            script += self._build_flatpak_section(flatpaks)

        # Footer
        script += """
echo ""
echo "================================================"
log_info "Restoration complete!"
log_info "Your system is ready to use."
echo "================================================"
"""

        return script

    def _build_aur_section(self, aur_packages: List[str]) -> str:
        """Build AUR installation section."""
        packages_str = self._quote_packages(aur_packages)
        return f"""# Step 3: Install AUR packages (Arch Linux)
log_info "Installing {len(aur_packages)} AUR packages..."
if command -v yay &> /dev/null; then
    if ! yay -S --needed --noconfirm {packages_str}; then
        log_warn "Some AUR packages may have failed to install"
    fi
    log_info "AUR package installation completed"
elif command -v paru &> /dev/null; then
    if ! paru -S --needed --noconfirm {packages_str}; then
        log_warn "Some AUR packages may have failed to install"
    fi
    log_info "AUR package installation completed (using paru)"
else
    log_error "Neither yay nor paru found. Install an AUR helper to proceed."
fi
echo ""
"""

    def _build_flatpak_section(self, flatpaks: List[str]) -> str:
        """Build Flatpak installation section."""
        packages_str = self._quote_packages(flatpaks)
        return f"""# Step 4: Install Flatpak applications
log_info "Installing {len(flatpaks)} Flatpak applications..."
if command -v flatpak &> /dev/null; then
    log_info "Adding flathub remote if not present..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true
    
    if ! flatpak install -y flathub {packages_str}; then
        log_warn "Some Flatpak applications may have failed to install"
    fi
    log_info "Flatpak installation completed"
else
    log_error "Flatpak is not installed. Please install it manually."
fi
echo ""
"""

    def _quote_packages(self, packages: List[str]) -> str:
        """
        Safely quote packages for shell execution.

        Args:
            packages: List of package names

        Returns:
            Space-separated quoted package names
        """
        return " ".join(shlex.quote(pkg) for pkg in packages)

    def _get_update_command(self) -> str:
        """Get system update command for current distro."""
        cmd = UPDATE_COMMANDS.get(self.sys.distro, UPDATE_COMMANDS.get("debian"))
        return cmd if cmd else "echo 'No update command available'"

    def _get_install_command(self, packages: List[str]) -> str:
        """
        Get package install command for current distro.

        Args:
            packages: List of packages to install

        Returns:
            Complete install command
        """
        if not packages:
            return "echo 'No packages to install'"

        base_cmd = INSTALL_COMMANDS.get(
            self.sys.distro, INSTALL_COMMANDS.get("debian")
        )
        packages_str = self._quote_packages(packages)
        return f"{base_cmd} {packages_str}" if base_cmd else "echo 'Error: Unknown distro'"

    def _write_script(self, content: str) -> None:
        """
        Write script to file and set permissions.

        Args:
            content: Script content to write

        Raises:
            IOError: If file writing fails
        """
        try:
            with open(self.filename, "w", encoding=SCRIPT_ENCODING) as f:
                f.write(content)
            os.chmod(self.filename, SCRIPT_PERMISSIONS)
            logger.info(f"Script written to {self.filename} with executable permissions")
        except IOError as e:
            logger.error(f"Failed to write script file: {e}")
            raise
