"""Script generation and export module."""

import os
import shlex
from datetime import datetime
from typing import List, Optional
from constants import (
    UPDATE_COMMANDS,
    INSTALL_COMMANDS,
    SCRIPT_PREFIX,
    SCRIPT_EXTENSION,
    SCRIPT_ENCODING,
    SCRIPT_PERMISSIONS,
)
from core.detector import SystemInfo
from core.config import SystemConfig
from tui.interface import TUI
from logger import get_logger

logger = get_logger(__name__)

__all__ = ["ScriptExporter"]


class ScriptExporter:
    """
    Generates restoration scripts based on system information and packages.

    Attributes:
        sys: SystemInfo instance
        filename: Generated script filename
    """

    def __init__(self, sys_info: SystemInfo) -> None:
        """
        Initialize ScriptExporter.

        Args:
            sys_info: SystemInfo instance with system details
        """
        self.sys = sys_info
        timestamp = datetime.now().strftime("%Y%m%d")
        self.filename = f"{SCRIPT_PREFIX}{timestamp}{SCRIPT_EXTENSION}"
        logger.info(f"ScriptExporter initialized for {self.sys.distro}")

    def confirm(self, prompt: str) -> bool:
        """
        Ask user for confirmation using fzf.

        Args:
            prompt: Question to display to user

        Returns:
            True if user selected "Yes", False otherwise
        """
        try:
            choice = TUI.run_fzf(["Yes", "No"], prompt=prompt)
            result = choice == "Yes"
            logger.debug(f"User confirmation for '{prompt}': {result}")
            return result
        except Exception as e:
            logger.error(f"Error during confirmation: {e}")
            return False

    def generate_script(
        self, packages: List[str], aur_packages: List[str], flatpaks: List[str], system_config: Optional[SystemConfig] = None
    ) -> Optional[str]:
        """
        Generate restoration script with all collected data.

        Args:
            packages: List of native packages
            aur_packages: List of AUR packages
            flatpaks: List of Flatpak applications
            system_config: Optional system configuration to include

        Returns:
            Path to generated script, None if generation failed

        Raises:
            ValueError: If input lists are invalid
        """
        if not isinstance(packages, list):
            raise ValueError("packages must be a list")
        if not isinstance(aur_packages, list):
            raise ValueError("aur_packages must be a list")
        if not isinstance(flatpaks, list):
            raise ValueError("flatpaks must be a list")

        try:
            script_content = self._build_script(packages, aur_packages, flatpaks, system_config)
            self._write_script(script_content)
            logger.info(f"Script generated successfully: {self.filename}")
            return self.filename
        except Exception as e:
            logger.error(f"Failed to generate script: {e}")
            return None

    def _build_script(
        self, packages: List[str], aur_packages: List[str], flatpaks: List[str], system_config: Optional[SystemConfig] = None
    ) -> str:
        """
        Build script content.

        Args:
            packages: List of native packages
            aur_packages: List of AUR packages
            flatpaks: List of Flatpak applications
            system_config: Optional system configuration to include

        Returns:
            Complete script content as string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        script = f"""#!/bin/bash
# {'-' * 60}
# {self.sys.name} - System Restoration Script
# Generated by DSXConfig v2.0.0
# Timestamp: {timestamp}
# Distro: {self.sys.distro} | Package Manager: {self.sys.pkg_mgr}
# {'-' * 60}

set -e  # Exit on error
set -u  # Exit on undefined variable

# System detection
detect_system() {{
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        DISTRO_ID=$ID
        PRETTY_NAME=$PRETTY_NAME
    else
        DISTRO_ID="unknown"
        PRETTY_NAME="Unknown Linux"
    fi

    # Detect package manager
    if command -v pacman >/dev/null 2>&1; then
        PKG_MGR="pacman"
    elif command -v apt >/dev/null 2>&1; then
        PKG_MGR="apt"
    elif command -v dnf >/dev/null 2>&1; then
        PKG_MGR="dnf"
    else
        PKG_MGR="unknown"
    fi
}}

get_update_command() {{
    case "$DISTRO_ID" in
        arch|archlinux)
            echo "sudo pacman -Syu --noconfirm"
            ;;
        fedora|rhel|centos)
            echo "sudo dnf update -y"
            ;;
        debian|ubuntu|linuxmint)
            echo "sudo apt update && sudo apt upgrade -y"
            ;;
        *)
            echo "echo 'No update command available for $DISTRO_ID'"
            ;;
    esac
}}

# Call detection
detect_system

echo "================================================"
echo "  DSXConfig System Restoration"
echo "  Target: $PRETTY_NAME"
echo "================================================"
echo ""

# Color codes
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'  # No Color

# Logging functions
VERBOSE=false

select_log_mode() {{
    if command -v fzf >/dev/null 2>&1; then
        answer=$(printf "Sim\nNao" | fzf --no-multi --height 4 --border --prompt "Mostrar logs de instalacao? ")
        [ "$answer" = "Sim" ] && VERBOSE=true
    else
        read -p "Mostrar logs de instalacao? [s/N] " answer
        if [[ "$answer" =~ ^[sS](im)?$ ]]; then
            VERBOSE=true
        fi
    fi
}}

progress_bar() {{
    local current=$1
    local total=$2
    local width=40
    local filled=$(( current * width / total ))
    local empty=$(( width - filled ))
    local percent=$(( current * 100 / total ))
    printf "\rProgress: ["
    for i in $(seq 1 $filled); do printf "#"; done
    for i in $(seq 1 $empty); do printf "-"; done
    printf "] %3d%%" "$percent"
    if [ "$current" -ge "$total" ]; then echo; fi
}}

log_info() {{
    if [ "$VERBOSE" = "true" ]; then
        echo -e "${{GREEN}}[INFO]${{NC}} $1"
    fi
}}

log_warn() {{
    echo -e "${{YELLOW}}[WARN]${{NC}} $1"
}}

log_error() {{
    echo -e "${{RED}}[ERROR]${{NC}} $1"
}}

select_log_mode

# Step 1: Update system
log_info "Updating system repositories..."
UPDATE_CMD=$(get_update_command)
if ! eval "$UPDATE_CMD"; then
    log_error "Failed to update system"
    exit 1
fi
log_info "System update completed"
echo ""

# Adaptive package mapping for cross-distro resiliency
TARGET_PKG_MGR="$PKG_MGR"

map_package() {{
    local pkg="$1"
    local target_pkg="$pkg"

    case "$pkg" in
        python)
            if [ "$TARGET_PKG_MGR" = "pacman" ]; then
                target_pkg="python"
            else
                target_pkg="python3"
            fi
            ;;
        python-pip)
            target_pkg="python3-pip";
            ;;
        libreoffice-fresh)
            target_pkg="libreoffice";
            ;;
        google-chrome|google-chrome-stable)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="google-chrome-stable"
                    ;;
                dnf)
                    target_pkg="google-chrome-stable"
                    ;;
                pacman)
                    target_pkg="google-chrome"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        docker)
            if [ "$TARGET_PKG_MGR" = "apt" ]; then
                target_pkg="docker.io"
            else
                target_pkg="docker"
            fi
            ;;
        openssh)
            target_pkg="openssh-server";
            ;;
        code|vscode|visual-studio-code)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="code"
                    ;;
                dnf)
                    target_pkg="code"
                    ;;
                pacman)
                    target_pkg="visual-studio-code-bin"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        github-desktop|github-desktop-bin)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="github-desktop"
                    ;;
                dnf)
                    target_pkg="github-desktop"
                    ;;
                pacman)
                    target_pkg="github-desktop-bin"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        spotify)
            case "$TARGET_PKG_MGR" in
                apt)
                    target_pkg="spotify-client"
                    ;;
                dnf)
                    target_pkg="spotify-client"
                    ;;
                pacman)
                    target_pkg="spotify"
                    ;;
                *)
                    target_pkg="$pkg"
                    ;;
            esac
            ;;
        obsidian)
            target_pkg="obsidian";
            ;;
        *)
            target_pkg="$pkg";
            ;;
    esac

    echo "$target_pkg"
}}

package_available() {{
    local pkg="$1"
    case "$TARGET_PKG_MGR" in
        pacman)
            pacman -Si "$pkg" >/dev/null 2>&1
            ;;
        apt)
            apt-cache show "$pkg" >/dev/null 2>&1
            ;;
        dnf)
            dnf list --available "$pkg" >/dev/null 2>&1
            ;;
        *)
            return 1
            ;;
    esac
}}

check_flatpak() {{
    local pkg="$1"
    flatpak search "$pkg" --columns=application | grep -q "^$pkg$" 2>/dev/null
}}

check_snap() {{
    local pkg="$1"
    snap find "$pkg" | grep -q "^$pkg " 2>/dev/null
}}

check_aur() {{
    local pkg="$1"
    # Simple check if AUR package exists (requires yay/paru or similar)
    if command -v yay >/dev/null 2>&1; then
        yay -Si "$pkg" >/dev/null 2>&1
    elif command -v paru >/dev/null 2>&1; then
        paru -Si "$pkg" >/dev/null 2>&1
    else
        return 1
    fi
}}

find_installation_methods() {{
    local pkg="$1"
    local methods=""

    if package_available "$pkg"; then
        methods="${{methods}}native "
    fi

    if check_flatpak "$pkg"; then
        methods="${{methods}}flatpak "
    fi

    if [ "$TARGET_PKG_MGR" = "apt" ] && check_snap "$pkg"; then
        methods="${{methods}}snap "
    fi

    if [ "$TARGET_PKG_MGR" = "pacman" ] && check_aur "$pkg"; then
        methods="${{methods}}aur "
    fi

    echo "$methods" | tr ' ' '\n' | grep -v '^$'
}}

choose_installation_method() {{
    local pkg="$1"
    local methods="$2"

    if [ -z "$methods" ]; then
        log_error "Nenhum metodo de instalacao encontrado para $pkg"
        return 1
    fi

    local method_count=$(echo "$methods" | wc -l)

    if [ "$method_count" -eq 1 ]; then
        echo "$methods"
        return 0
    fi

    log_info "Multiplos metodos disponiveis para $pkg:"
    echo "$methods" | nl -w2 -s') '

    if command -v fzf >/dev/null 2>&1; then
        local choice=$(echo "$methods" | fzf --no-multi --height 10 --border --prompt "Escolha metodo para $pkg: ")
        echo "$choice"
    else
        local choice
        read -p "Escolha numero do metodo para $pkg: " choice_num
        echo "$methods" | sed -n "${{choice_num}}p"
    fi
}}

install_with_method() {{
    local pkg="$1"
    local method="$2"

    case "$method" in
        native)
            case "$TARGET_PKG_MGR" in
                pacman)
                    sudo pacman -S --needed --noconfirm "$pkg"
                    ;;
                apt)
                    sudo apt install -y "$pkg"
                    ;;
                dnf)
                    sudo dnf install -y "$pkg"
                    ;;
                *)
                    log_error "Gerenciador de pacotes nao suportado: $TARGET_PKG_MGR"
                    return 1
                    ;;
            esac
            ;;
        flatpak)
            flatpak install -y flathub "$pkg"
            ;;
        snap)
            sudo snap install "$pkg"
            ;;
        aur)
            if command -v yay >/dev/null 2>&1; then
                yay -S --needed --noconfirm "$pkg"
            elif command -v paru >/dev/null 2>&1; then
                paru -S --needed --noconfirm "$pkg"
            else
                log_error "Nenhum helper AUR encontrado (yay/paru)"
                return 1
            fi
            ;;
        *)
            log_error "Metodo desconhecido: $method"
            return 1
            ;;
    esac
}}

suggest_alternatives() {{
    local pkg="$1"
    case "$pkg" in
        code|vscode|visual-studio-code)
            log_info "Alternativas para VSCode: flatpak install code, snap install code, ou baixar .deb/.rpm do site oficial"
            ;;
        google-chrome|chromium)
            log_info "Alternativas para Chrome: chromium-browser (apt), chromium (dnf), ou flatpak install com.google.Chrome"
            ;;
        obsidian)
            log_info "Alternativas para Obsidian: flatpak install md.obsidian.Obsidian"
            ;;
        discord)
            log_info "Alternativas para Discord: flatpak install com.discordapp.Discord"
            ;;
        spotify)
            log_info "Alternativas para Spotify: flatpak install com.spotify.Client"
            ;;
        *)
            log_info "Tente flatpak search '$pkg' ou snap find '$pkg' para alternativas"
            ;;
    esac
}}

install_google_chrome() {{
    # ask once per script if user wants this behavior
    read -p "Instalar Google Chrome via repositorio oficial para $TARGET_PKG_MGR? [S/n] " choice
    if [[ "$choice" =~ ^[nN] ]]; then
        return 0
    fi

    case "$TARGET_PKG_MGR" in
        apt)
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /etc/apt/keyrings/google-linux-signing-key.gpg
            echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt update
            sudo apt install -y google-chrome-stable
            ;;
        dnf)
            sudo tee /etc/yum.repos.d/google-chrome.repo >/dev/null <<'EOF'
[google-chrome]
name=google-chrome - x86_64
baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
EOF
            sudo dnf install -y google-chrome-stable
            ;;
        pacman)
            log_warn "Use AUR helper para instalar google-chrome no Arch.";
            return 1;
            ;;
        *)
            log_error "Google Chrome nao suportado para $TARGET_PKG_MGR";
            return 1;
            ;;
    esac
}}

install_vscode() {{
    # ask once per script if user wants this behavior
    read -p "Instalar VSCode via repositorio oficial da Microsoft para $TARGET_PKG_MGR? [S/n] " choice
    if [[ "$choice" =~ ^[nN] ]]; then
        return 0
    fi

    case "$TARGET_PKG_MGR" in
        apt)
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /etc/apt/keyrings/packages.microsoft.gpg
            echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main' | sudo tee /etc/apt/sources.list.d/vscode.list
            sudo apt update
            sudo apt install -y code
            ;;
        dnf)
            sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
            sudo tee /etc/yum.repos.d/vscode.repo >/dev/null <<'EOF'
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
EOF
            sudo dnf install -y code
            ;;
        pacman)
            log_warn "Use AUR helper para instalar vscode no Arch.";
            return 1;
            ;;
        *)
            log_error "VSCode nao suportado para $TARGET_PKG_MGR";
            return 1;
            ;;
    esac
}}

install_package() {{
    local pkg="$1"

    if [ "$pkg" = "google-chrome" ] || [ "$pkg" = "google-chrome-stable" ]; then
        install_google_chrome
        return
    fi
    if [ "$pkg" = "code" ] || [ "$pkg" = "vscode" ] || [ "$pkg" = "visual-studio-code" ]; then
        install_vscode
        return
    fi

    local methods=$(find_installation_methods "$pkg")
    if [ -z "$methods" ]; then
        log_error "Pacote $pkg nao encontrado em nenhuma fonte disponivel"
        log_info "Tentando alternativas logicas..."
        suggest_alternatives "$pkg"
        return 1
    fi

    local chosen_method=$(choose_installation_method "$pkg" "$methods")
    if [ -z "$chosen_method" ]; then
        log_warn "Instalacao de $pkg cancelada pelo usuario"
        return 1
    fi

    log_info "Instalando $pkg via $chosen_method"
    if ! install_with_method "$pkg" "$chosen_method"; then
        log_error "Falha ao instalar $pkg via $chosen_method"
        return 1
    fi
}}

PACKAGES=({self._quote_packages(packages)})

# Step 2: Install native packages
if [ ${{#PACKAGES[@]}} -gt 0 ]; then
    total=${{#PACKAGES[@]}}
    current=0
    for original in "${{PACKAGES[@]}}"; do
        current=$((current + 1))
        progress_bar "$current" "$total"

        candidate="$(map_package "$original")"

        if package_available "$candidate"; then
            if [ "$VERBOSE" = "true" ]; then
                log_info "Instalando pacote resolvido '$candidate' de '$original'"
            fi
            if ! install_package "$candidate"; then
                log_warn "Falha ao instalar '$candidate'"
            fi
        else
            log_warn "Pulando '$original' (nao disponivel como '$candidate')"
        fi
    done
    progress_bar "$total" "$total"
else
    log_warn "No native packages to install"
fi

echo ""
"""

        # Add AUR section if applicable
        if aur_packages:
            script += self._build_aur_section(aur_packages)

        # Add Flatpak section
        if flatpaks:
            script += self._build_flatpak_section(flatpaks)

        # Add system configuration section
        if system_config:
            script += self._build_config_section(system_config)

        # Footer
        script += """
echo ""
echo "================================================"
log_info "Restoration complete!"
log_info "Your system is ready to use."
echo "================================================"
"""

        return script

    def _build_aur_section(self, aur_packages: List[str]) -> str:
        """Build AUR installation section."""
        packages_str = self._quote_packages(aur_packages)
        section = """# Step 3: Install AUR packages (Arch Linux)
install_aur_helper() {
    if command -v yay &> /dev/null; then
        return 0
    fi
    if command -v paru &> /dev/null; then
        return 0
    fi

    log_info \"No AUR helper found. Installing paru by default...\"
    if ! command -v pacman &> /dev/null; then
        log_error \"pacman not available, cannot install AUR helper.\"
        return 1
    fi

    sudo pacman -S --needed --noconfirm git base-devel || return 1
    tmpdir=$(mktemp -d)
    git clone https://aur.archlinux.org/paru.git \"$tmpdir/paru\" || {
        rm -rf \"$tmpdir\"
        log_error \"Failed to clone paru repository.\"
        return 1
    }

    cd \"$tmpdir/paru\" || return 1
    makepkg -si --noconfirm || {
        log_error \"Failed to build/install paru.\"
        cd - >/dev/null 2>&1
        rm -rf \"$tmpdir\"
        return 1
    }
    cd - >/dev/null 2>&1
    rm -rf \"$tmpdir\"
    return 0
}

if [ \"$DISTRO_ID\" = \"arch\" ] || [ \"$DISTRO_ID\" = \"archlinux\" ]; then
    log_info \"Installing {{AUR_COUNT}} AUR packages...\"
    if ! install_aur_helper; then
        log_error \"AUR helper install failed. Skipping AUR packages.\"
        log_warn \"Please install yay or paru and rerun script if needed.\"
    else
        if command -v yay &> /dev/null; then
            aur_cmd=\"yay\"
        elif command -v paru &> /dev/null; then
            aur_cmd=\"paru\"
        else
            aur_cmd=\"\"
        fi

        if [ -n \"$aur_cmd\" ]; then
            if ! $aur_cmd -S --needed --noconfirm {{AUR_PKGS}}; then
                log_warn \"Some AUR packages may have failed to install\"
            else
                log_info \"AUR package installation completed (using $aur_cmd)\"
            fi
        else
            log_error \"AUR helper command not found after installation attempts.\"
        fi
    fi
else
    log_warn \"AUR packages skipped (not Arch Linux)\"
fi
"""
        return section.replace("{{AUR_COUNT}}", str(len(aur_packages))).replace(
            "{{AUR_PKGS}}", packages_str
        )


    def _build_flatpak_section(self, flatpaks: List[str]) -> str:
        """Build Flatpak installation section."""
        packages_str = self._quote_packages(flatpaks)
        return f"""# Step 4: Install Flatpak applications
log_info "Installing {len(flatpaks)} Flatpak applications..."
if command -v flatpak &> /dev/null; then
    log_info "Adding flathub remote if not present..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true
    
    if ! flatpak install -y flathub {packages_str}; then
        log_warn "Some Flatpak applications may have failed to install"
    fi
    log_info "Flatpak installation completed"
else
    log_error "Flatpak is not installed. Please install it manually."
fi
echo ""
"""

    def _build_config_section(self, system_config: SystemConfig) -> str:
        """Build system configuration restoration section."""
        config_lines = []

        # Add shell configuration
        if system_config.shell:
            config_lines.append(f"log_info \"Setting user shell to {system_config.shell}...\"")
            config_lines.append(f"chsh -s /bin/{system_config.shell} || log_warn \"Failed to set shell\"")

        # Add terminal configuration (if detected)
        if system_config.terminal and system_config.terminal != "unknown":
            config_lines.append(f"log_info \"Detected terminal: {system_config.terminal}\"")
            config_lines.append("# Note: Terminal configuration may need manual setup")

        # Add environment variables
        if system_config.environment_vars:
            config_lines.append("log_info \"Setting environment variables...\"")
            for var, value in system_config.environment_vars.items():
                if var == "PATH":
                    # Handle PATH specially to avoid overriding system PATH
                    config_lines.append(f"export {var}=\"{value}:$PATH\"")
                else:
                    config_lines.append(f"export {var}=\"{value}\"")
            # Add to .bashrc if it exists
            config_lines.append("if [ -f ~/.bashrc ]; then")
            for var, value in system_config.environment_vars.items():
                if var == "PATH":
                    config_lines.append(f"    echo 'export {var}=\"{value}:$PATH\"' >> ~/.bashrc")
                else:
                    config_lines.append(f"    echo 'export {var}=\"{value}\"' >> ~/.bashrc")
            config_lines.append("fi")

        # Add config files restoration
        if system_config.config_files:
            config_lines.append("log_info \"Restoring configuration files...\"")
            for file_path, content in system_config.config_files.items():
                # Create directory if needed
                dir_path = os.path.dirname(file_path)
                if dir_path != "~":
                    config_lines.append(f"mkdir -p {dir_path}")
                # Write content using cat with heredoc
                config_lines.append(f"cat > {file_path} << 'EOF'")
                # Escape single quotes in content
                escaped_content = content.replace("'", "'\"'\"'")
                config_lines.append(escaped_content)
                config_lines.append("EOF")
                config_lines.append(f"log_info \"Restored {os.path.basename(file_path)}\"")

        if config_lines:
            section = f"""# Step 5: Restore System Configuration
log_info "Restoring system configuration..."
{"\n".join(config_lines)}
log_info "System configuration restored"
echo ""
"""
            return section
        else:
            return ""

    def _quote_packages(self, packages: List[str]) -> str:
        """
        Safely quote packages for shell execution.

        Args:
            packages: List of package names

        Returns:
            Space-separated quoted package names
        """
        return " ".join(shlex.quote(pkg) for pkg in packages)

    def _get_update_command(self) -> str:
        """Get system update command for current distro."""
        cmd = UPDATE_COMMANDS.get(self.sys.distro, UPDATE_COMMANDS.get("debian"))
        return cmd if cmd else "echo 'No update command available'"

    def _get_install_command(self, packages: List[str]) -> str:
        """
        Get package install command for current distro.

        Args:
            packages: List of packages to install

        Returns:
            Complete install command
        """
        if not packages:
            return "echo 'No packages to install'"

        base_cmd = INSTALL_COMMANDS.get(
            self.sys.distro, INSTALL_COMMANDS.get("debian")
        )
        packages_str = self._quote_packages(packages)
        return f"{base_cmd} {packages_str}" if base_cmd else "echo 'Error: Unknown distro'"

    def _write_script(self, content: str) -> None:
        """
        Write script to file and set permissions.

        Args:
            content: Script content to write

        Raises:
            IOError: If file writing fails
        """
        try:
            with open(self.filename, "w", encoding=SCRIPT_ENCODING) as f:
                f.write(content)
            os.chmod(self.filename, SCRIPT_PERMISSIONS)
            logger.info(f"Script written to {self.filename} with executable permissions")
        except IOError as e:
            logger.error(f"Failed to write script file: {e}")
            raise
